library(MASS)
library(pscl)
library(sandwich)
library(car)
library(lmtest)
library(MixAll)
dt<-DebTrivedi[,c(1,6:8,13,15,18)]
plot(table(dt$ofp),xlab="Number of physician office vists",ylab="Frequency")
plot(ofp~numchron,data=dt)
clog<-function(x) log(x+0.5)
cfac<-function(x,breaks=NULL){
  if(is.null(breaks))breaks<-unique(quantile(x,0:10/10))
  x<-cut(x,breaks,include.lowest=T,right=F)
  levels(x)<-paste(breaks[-length(breaks)],ifelse(diff(breaks)>1,c(paste("-",breaks[-c(1,length(breaks))]-1,sep = ""),"+"),""),sep="")
  return(x)
}
opar<-par(no.readonly = TRUE)
par(mfrow=c(3,2))
plot(clog(ofp)~cfac(numchron),data=dt,xlab="Number of chronic conditions",ylab="Number of physician office visits",main="numchron")
plot(clog(ofp)~health,data=dt,varwidth=T,xlab="Self-perceived health status",ylab="Number of physician office visits",main="health")
plot(clog(ofp)~privins,data=dt,varwidth=T,xlab="Covered by private insurance",ylab="Number of physician office visits",main="privins")
plot(clog(ofp)~cfac(hosp,c(0:2,8)),data=dt,xlab="Number of hospital stays",ylab="Number of physician office visits",main="hosp")
plot(clog(ofp)~gender,data=dt,varwidth=T,xlab="Gender",ylab="Number of physician office visits",main="gender")
plot(cfac(ofp,c(0:2,4,6,10,100))~school,data=dt,breaks=9,xlab="Number of years of education",ylab="Number of physician office visits",main="school")
par(opar)
##poisson regression
fm_pois<-glm(ofp~.,data=dt,family = poisson)
summary(fm_pois)
coeftest(fm_pois,vcov=sandwich)
##quasipoisson
fm_qpois <- glm(ofp ~ ., data = dt, family = quasipoisson)
summary(fm_qpois)
##negative binomial regression
fm_nbin<-glm.nb(ofp~.,data=dt)
summary(fm_nbin,correlation=F)
##hurdle regression
fm_hurdle0<-hurdle(ofp~.,data=dt,dist = "negbin")
summary(fm_hurdle0)
fm_hurdle<-hurdle(ofp~.|hosp+numchron+privins+school+gender,data=dt,dist="negbin")
summary(fm_hurdle)
waldtest(fm_hurdle0,fm_hurdle)
lrtest(fm_hurdle0,fm_hurdle)
##zero-inflated regression
fm_zinb0<-zeroinfl(ofp~.,data=dt,dist = "negbin")
fm_zinb<-zeroinfl(ofp~.|hosp+numchron+privins+school+gender,data=dt,dist = "negbin")
waldtest(fm_zinb0,fm_zinb)
lrtest(fm_zinb0,fm_zinb)
summary(fm_zinb)
##comparison
fm<-list("ML-pois"=fm_pois,"Quasi-Pois" = fm_qpois,NB=fm_nbin,"Hurdle-NB"=fm_hurdle,ZINB=fm_zinb)
round(sapply(fm,function(x)coef(x)[1:8]),digits = 3)
round(cbind("ML-pois"=sqrt(diag(vcov(fm_pois))),"Adj-Pois" = sqrt(diag(sandwich(fm_pois))),sapply(fm[-1],function(x)sqrt(diag(vcov(x)))[1:8])),digits = 3)
rbind(logLik=sapply(fm,function(x)round(logLik(x),digits=0)),Df=sapply(fm,function(x)attr(logLik(x),"df")))
round(c(Obs = sum(dt$ofp < 1), "ML-Pois" = sum(dpois(0, fitted(fm_pois))),"Adj-Pois" = NA,"Quasi-Pois" = NA,NB = sum(dnbinom(0, mu = fitted(fm_nbin), size = fm_nbin$theta)),"NB-Hurdle" = sum(predict(fm_hurdle, type = "prob")[, 1]),ZINB = sum(predict(fm_zinb, type = "prob")[, 1])))
t(sapply(fm[4:5], function(x) round(x$coefficients$zero, digits = 3)))
